---
dataset_mode: mix

checkpoints: './checkpoints/final_test'
model_name: &MODEL_NAME SemiSyn_DMPHN_pair3_unpair1
MPR_model: './pretrain_models/MPRnet/model_deblurring.pth'
DMPHN_model: './pretrain_models/DMPHN/G_net_latest.pth'
model_class: Baseline_MAP
resume_train: False 
which_epoch: latest
start_epoch: 0
save_epoch: 20
display_freq: 20
val_freq: 4
crop_size_X: 256
crop_size_Y: 256
gpu: [1]
input_nc: 3
output_nc: 3
init_type: xavier
init_gain: 0.02
epoch: 400
batch_size: 4
is_training: true
iteration_G: 1
load_only_G: True

train:
  blur_videos: /home/yjz/hdd/deblur_datasets/Gopro_1080p/train/**/blur/*.png
  deblur_videos: /home/yjz/hdd/deblur_datasets/Gopro_1080p/train/**/sharp/*.png
  real_blur_videos: /home/yjz/hdd/deblur_datasets/Synthetic_blur/Gao/*blurryimg.png
  sharp_videos: /home/yjz/hdd/deblur_datasets/Synthetic_blur/Gao/*gtimg.png
  lr_D: 0.0001
  lr_G: 0.00005
  lr_M: 0.0001
  beta1: 0.9
  optimizer: adam
  scheduler: linear
  warmup_epoch: 0
  relative_reblur: true
  identical_loss: false
  lambda_G_f_sharp: 0.5
  lambda_G_idt: 0
  lambda_G_tv: 0
  lambda_G_Itv: 0
  lambda_G_content: 100
  lambda_G_reblur: 10
  lambda_G_global: 1
  lambda_M_reblur: 1
  lambda_M_blur: 0.001
  lambda_M_f_sharp: 0.001
  lambda_M_sharp: 0.002
  lambda_M_tv: 0.002
  natural_D: true


val:
  val_batch_size: 1
  verbose: False
  blur_videos: /home/yjz/hdd/deblur_datasets/Gopro_1080p/test/**/blur/*.png
  deblur_videos: /home/yjz/hdd/deblur_datasets/Gopro_1080p/test/**/sharp/*.png
  real_blur_videos: /home/yjz/hdd/deblur_datasets/Synthetic_blur/test_small/*blurryimg.png
  sharp_videos: /home/yjz/hdd/deblur_datasets/Synthetic_blur/test_small/*gtimg.png

model:
  g_name: DMPHN
  d_name: Offset
  use_sigmoid: 0
  offset_mode: lin
  norm: 

test:
  result_dir: ./exp_results/RealBlur
  save_dir: *MODEL_NAME
  verbose: False
  test_batch_size: 1
  dataset_mode: pair
  which_epoch: latest
  blur_videos: /home/yjz/hdd/deblur_datasets/Synthetic_blur/test_small/*blurryimg.png
  deblur_videos: /home/yjz/hdd/deblur_datasets/Synthetic_blur/test_small/*gtimg.png
  real_blur_videos: /home/yjz/hdd/deblur_datasets/S10_blur_set/train/**/*.png





