---
dataset_mode: pair

checkpoints: './checkpoints/tensorboard-MPRnet'
model_name: &MODEL_NAME MPRnet_GfS2_Itv2 
MPR_model: './pretrain_models/MPRnet/model_deblurring.pth'
DMPHN_model: './pretrain_models/DMPHN/G_net_latest.pth'
model_class: MPRnet_finetune
resume_train: False
which_epoch: latest 
start_epoch: 0
save_epoch: 10
display_freq: 100
val_freq: 2
crop_size_X: 256
crop_size_Y: 256
gpu: [0]
input_nc: 3
output_nc: 3
init_type: xavier
init_gain: 0.02
epoch: 1000
batch_size: 8
is_training: true
iteration_G: 1 
load_only_G: False

model:
  g_name: MPRnet
  d_name: Offset
  use_sigmoid: 0
  norm: 

test:
  result_dir: ./exp_results/MPRnet
  save_dir: *MODEL_NAME 
  which_epoch: latest
  verbose: False
  test_batch_size: 1
  dataset_mode: unpair
  blur_videos: /home/yjz/hdd/deblur_datasets/RealBlur/RealBlur-J_dataset/test/input/*.png
  deblur_videos: /home/yjz/hdd/deblur_datasets/RealBlur/RealBlur-J_dataset/test/target/*.png
  real_blur_videos: /home/yjz/datasets/S10_finetune_set/Real_test/*/*.png 
  sharp_videos: /home/yjz/datasets/S10_finetune_set/Real_test/*/*.png 

