---
dataset_mode: pair

checkpoints: './checkpoints/Quad_deblur'
model_name: &MODEL_NAME DMPHN_lin_baseline
model_class: Baseline_finetune
MPR_model: './pretrain_models/MPRnet/model_deblurring.pth'
DMPHN_model: './pretrain_models/DMPHN/G_net_latest.pth'
resume_train: False
which_epoch: latest 
start_epoch: 0
save_epoch: 10
display_freq: 100
val_freq: 2
crop_size_X: 256
crop_size_Y: 256
gpu: [0]
input_nc: 3
output_nc: 3
init_type: xavier
init_gain: 0.02
epoch: 1000
batch_size: 8
is_training: true
iteration_G: 1 
load_only_G: false

train:
  relative_reblur: true

model:
  g_name: DMPHN
  d_name: Offset
  use_sigmoid: 0
  norm: 
  offset_mode: lin

test:
  result_dir: ./exp_results/Quad_deblur
  save_dir: *MODEL_NAME 
  verbose: true 
  which_epoch: latest
  test_batch_size: 1
  dataset_mode: unpair
  blur_videos: /hdd/deblur_datasets/RealBlur/RealBlur-J_dataset/test/input/*.png
  deblur_videos: /hdd/deblur_datasets/RealBlur/RealBlur-J_dataset/test/target/*.png
  real_blur_videos: /hdd/deblur_datasets/Deblur_whole/test/GOPRO/input/*.png
  sharp_videos: /hdd/deblur_datasets/Deblur_whole/test/GOPRO/target/*.png
