---
dataset_mode: pair

checkpoints: './checkpoints/Best_train'
model_name: &MODEL_NAME RealBlur-J_DMPHN_mixdata 
MPR_model: './pretrain_models/MPRnet/model_deblurring.pth'
DMPHN_model: './pretrain_models/DMPHN/G_net_latest.pth'
model_class: Baseline_finetune_unpair
resume_train: False
which_epoch: latest 
start_epoch: 0
save_epoch: 10
display_freq: 100
val_freq: 2
crop_size_X: 256
crop_size_Y: 256
gpu: [0]
input_nc: 3
output_nc: 3
init_type: xavier
init_gain: 0.02
epoch: 1000
batch_size: 8
is_training: true
iteration_G: 1 
load_only_G: False
model:
  g_name: DMPHN
  d_name: Offset
  use_sigmoid: 0
  norm: 
  offset_mode: lin

train:
  blur_videos: /hdd/deblur_datasets/Gopro_1080p/train/**/blur/*.png
  deblur_videos: /hdd/deblur_datasets/Gopro_1080p/train/**/sharp/*.png
  real_blur_videos: /home/yjz/hdd/deblur_datasets/Synthetic_blur/Gao/*blurryimg.png
  sharp_videos: /home/yjz/hdd/deblur_datasets/Synthetic_blur/Gao/*gtimg.png
  lr_D: 0.00001
  lr_G: 0.00002
  lr_M: 0.0
  beta1: 0.9
  optimizer: adam
  scheduler: linear
  warmup_epoch: 0
  relative_reblur: true
  absolute_reblur: false
  identical_loss: false
  lambda_G_f_sharp: 1
  lambda_G_idt: 0
  lambda_G_tv: 1
  lambda_G_Itv: 10
  lambda_G_teacher: 0
  lambda_G_reblur: 10
  lambda_G_global: 0.1
  lambda_M_reblur: 1
  lambda_M_blur: 0.002
  lambda_M_f_sharp: 0.001
  lambda_M_sharp: 0.002
  lambda_M_tv: 0.0002
  global_D: true

test:
  result_dir: ./exp_results/Multi_inference
  save_dir: *MODEL_NAME 
  which_epoch: latest
  verbose: False
  test_batch_size: 1
  dataset_mode: pair
  inference_num: 8
  blur_videos: /home/yjz/hdd/deblur_datasets/RealBlur/RealBlur-J_dataset/test/input/*.png
  deblur_videos: /home/yjz/hdd/deblur_datasets/RealBlur/RealBlur-J_dataset/test/target/*.png
  real_blur_videos: /home/yjz/datasets/S10_finetune_set/Real_test/*/*.png 
  sharp_videos: /home/yjz/datasets/S10_finetune_set/Real_test/*/*.png 

