---
dataset_mode: pair

checkpoints: './checkpoints/final_test'
model_name: &MODEL_NAME SemiSyn_DMPHN_p25_0702
MPR_model: './pretrain_models/MPRnet/model_deblurring.pth'
DMPHN_model: './pretrain_models/DMPHN/G_net_latest.pth'
model_class: Baseline_MAP
resume_train: False
which_epoch: best 
start_epoch: 0
save_epoch: 10
display_freq: 100
val_freq: 2
crop_size_X: 256
crop_size_Y: 256
gpu: [0]
input_nc: 3
output_nc: 3
init_type: xavier
init_gain: 0.02
epoch: 1000
batch_size: 8
is_training: true
iteration_G: 1 
load_only_G: False

model:
  g_name: DMPHN
  d_name: Offset
  use_sigmoid: 0
  offset_mode: lin
  norm: 

test:
  result_dir: ./results/final_test
  save_dir: *MODEL_NAME 
  which_epoch: 580
  verbose: False
  test_batch_size: 1
  dataset_mode: pair
  blur_videos: /home/yjz/datasets/Gopro_1080p/test/**/blur/*.png
  deblur_videos: /home/yjz/datasets/Gopro_1080p/test/**/sharp/*.png
  real_blur_videos: /home/yjz/datasets/S10_finetune_SsetReal_test/*/*.png 
  sharp_videos: /home/yjz/datasets/S10_finetune_set/Real_test/*/*.png 

